#! /usr/bin/bash
## Root directory of the playground
# NOTE: This can also be the absolute path to the playground directory
# Install compilers for arm  sudo apt-get install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
set -e

WORK_DIR=`pwd`

TARGET_ROOT="${WORK_DIR}/target_dir"
SOURCE_DIR="${WORK_DIR}/src"
BUILD_DIR="${WORK_DIR}/build"
ROOTFS_X86="${WORK_DIR}/rootfs_x86"
ROOTFS_ARM="${WORK_DIR}/rootfs_arm"
BLACKDUCK_PROJECT_NAME="canton-base-images"
