name: Sync and Trigger Build

on:
  push:
    branches:
      - release-line*
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - release-line*
      - main
  workflow_dispatch:

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: "DEBUG: Log event context"
        run: echo "${{ toJSON(github.event) }}"
      - name: Trigger build in dach-ny/da-base-images
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const payload = {
              sha: context.payload.pull_request?.head.sha || context.sha,
              ref: context.ref,
              event_name: context.eventName,
              base_ref: context.payload.pull_request?.base.ref,
              is_draft: context.payload.pull_request?.draft,
            };
            console.log("Sending payload:", payload);
            await github.rest.repos.createDispatchEvent({
              owner: 'dach-ny',
              repo: 'da-base-images',
              event_type: 'build-images',
              client_payload: {
                sha: payload 
              }
            });
