name: Test Release

on:
  release:
    types: [published]
jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: "DEBUG: Log event context"
        run: echo "${{ toJSON(github.event) }}"
      - name: Trigger build in dach-ny/da-base-images
        uses: actions/github-script@v9
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const payload = {
              sha: context.sha,
              ref: context.ref,
              repo: context.payload.repository.full_name,
              event_name: context.eventName,
              release: context.payload.release
            };
            console.log("Sending payload:", payload);
            console.log("Send Context:", context);
            await github.rest.repos.createDispatchEvent({
              owner: 'dach-ny',
              repo: 'da-base-images',
              event_type: 'build-release',
              client_payload: payload
            });
